### ISSUE TITLE
Unifi app keeps crashing

### ISSUE THREAD

**Issue by jaimevisser** [mnederlof/com.ubnt.unifi#8] opened 2017-05-30 20:53 UTC
On 1.3 RC9 the app keeps crashing every two hours. Sent a crash report.

**Comment by jaimevisser** [comment] 2017-08-21 07:45
Again not stable:
`
21/08/2017, 09:45:02 : [debug] There is no connection yet, please check your settings!
21/08/2017, 09:44:54 : [debug] Fatal error, not reconnecting...
21/08/2017, 09:44:54 : [debug] Updating status to Offline
21/08/2017, 09:44:54 : [debug] Got error while updating client list RequestError: getaddrinfo ENOTFOUND unipi unipi:8443
21/08/2017, 09:44:52 : [debug] Accesspoints received
21/08/2017, 09:44:51 : [debug] Updating offline clients
21/08/2017, 09:44:51 : [debug] Got client back undefined/Azha with mac 6c:ad:f8:1d:59:2d, idle: 0
21/08/2017, 09:44:45 : [debug] Polling clients (every 15 secs)
21/08/2017, 09:44:45 : [debug] Login success
21/08/2017, 09:44:45 : [debug] Updating status to Connected
21/08/2017, 09:44:43 : [debug] Fetching accesspoint list.
21/08/2017, 09:44:43 : [debug] Got login session
21/08/2017, 09:44:39 : [debug] Updating status to Connecting...
21/08/2017, 09:44:39 : [debug] Creating new controller connection
21/08/2017, 09:44:39 : [debug] Got new settings`

**Comment by mnederlof** [comment] 2017-12-08 10:43
Closing - not a bug - local address resolving goes wrong here.

**Closed by mnederlof** 2017-12-08 10:43 UTC
