### ISSUE TITLE
A lot of login messages after Controller update to version 5.9.29

### ISSUE THREAD

**Issue by arthurpoortman** [mnederlof/com.ubnt.unifi#31] opened 2018-10-23 22:19 UTC
Since the update of the Unifi controller to version 5.9.29 (coming from 5.8.00) i see a lot of login messages in the Events log on the controller from the account that  is used for the App, about 10-20 logins per minute.
I see no errors in the debug log of Homey., for now i disabled the app.

Best regards,

Arthur

**Comment by nombz** [comment] 2018-12-05 15:58
I bet that this is related to what I am seeing. I have a flow that triggers on a "DEvice just connected" and the filtered on a name and when that triggers a "Voice command" on Homey that welcomes the owner of the mobile that just connected home. After upgrace to 5.9.29 homey now greets the person with about 10-20 messages.

**Comment by mnederlof** [comment] 2020-02-12 22:52
As i do not have discovered this issue just yet, i cannot reproduce and have to close this issue for now.

**Closed as completed by mnederlof** 2020-02-12 22:52 UTC
